name: sonata
channels:
  - pytorch
  - nvidia/label/cuda-12.4.1
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cuda
  - conda-forge::cudnn
  - gcc=13.2
  - gxx=13.2
  - pytorch=2.5.0
  - torchvision=0.20.0
  - torchaudio=2.5.0
  - pytorch-cuda=12.4
  - numpy<=1.26.4  # for random seed
  - ninja
  - scipy
  - addict
  - timm
  - psutil
  - huggingface_hub
  - open3d  # for demo visualization
  - matplotlib  # for demo visualization
  - pip:
    - torch-scatter --find-links https://data.pyg.org/whl/torch-2.5.0+cu124.html
    - git+https://github.com/Dao-AILab/flash-attention.git
    - spconv-cu124
    - fast_pytorch_kmeans  # for demo visualization